### ISSUE TITLE
I can't use it on Windows 11

### ISSUE THREAD

**Issue by V1rtu0l** [janoglezcampos/DeathSleep#1]
![image](https://github.com/janoglezcampos/DeathSleep/assets/45991825/cdfe8bc8-50f1-4740-8a70-3ffffbe1d778)

**Comment by janoglezcampos** [comment]
Usually, this PoC not working comes from:
A) Not runnig the script for fixing the size of the stack frame.
B) RtlpTpTimerCallback not found because the pattern doesnt match, just ran it on W11, but had to modify the pattern mask to "xxxxxxxxxxxxxx-xxxxxxxxx" (only one byte changes, basically because the stack size for RtlpTpTimerCallback changes, [SUB RSP,0x40 -> SUB RSP,0x30]), if it doesnt work neither, you need to find the pattern by yourself, till RtlpTpTimerCallback is different than NULL.
